version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    rebase-strategy: auto
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
    rebase-strategy: auto
  - package-ecosystem: nix
    directory: /
    schedule:
      interval: monthly
    rebase-strategy: auto
